//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCast.VideoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VideoServiceReference.IVideoConferenceService", CallbackContract=typeof(AppCast.VideoServiceReference.IVideoConferenceServiceCallback))]
    public interface IVideoConferenceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/Subscribe", ReplyAction="http://tempuri.org/IVideoConferenceService/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/Subscribe", ReplyAction="http://tempuri.org/IVideoConferenceService/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/PublishVideo", ReplyAction="http://tempuri.org/IVideoConferenceService/PublishVideoResponse")]
        void PublishVideo(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/PublishVideo", ReplyAction="http://tempuri.org/IVideoConferenceService/PublishVideoResponse")]
        System.Threading.Tasks.Task PublishVideoAsync(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/PublishVoice", ReplyAction="http://tempuri.org/IVideoConferenceService/PublishVoiceResponse")]
        void PublishVoice(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/PublishVoice", ReplyAction="http://tempuri.org/IVideoConferenceService/PublishVoiceResponse")]
        System.Threading.Tasks.Task PublishVoiceAsync(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/PublishText", ReplyAction="http://tempuri.org/IVideoConferenceService/PublishTextResponse")]
        string PublishText(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/PublishText", ReplyAction="http://tempuri.org/IVideoConferenceService/PublishTextResponse")]
        System.Threading.Tasks.Task<string> PublishTextAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVideoConferenceServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/OnVideoSend", ReplyAction="http://tempuri.org/IVideoConferenceService/OnVideoSendResponse")]
        void OnVideoSend(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/OnVoiceSend", ReplyAction="http://tempuri.org/IVideoConferenceService/OnVoiceSendResponse")]
        void OnVoiceSend(byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoConferenceService/OnTextSend", ReplyAction="http://tempuri.org/IVideoConferenceService/OnTextSendResponse")]
        void OnTextSend(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVideoConferenceServiceChannel : AppCast.VideoServiceReference.IVideoConferenceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VideoConferenceServiceClient : System.ServiceModel.DuplexClientBase<AppCast.VideoServiceReference.IVideoConferenceService>, AppCast.VideoServiceReference.IVideoConferenceService {
        
        public VideoConferenceServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VideoConferenceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VideoConferenceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VideoConferenceServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VideoConferenceServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public void PublishVideo(byte[] data) {
            base.Channel.PublishVideo(data);
        }
        
        public System.Threading.Tasks.Task PublishVideoAsync(byte[] data) {
            return base.Channel.PublishVideoAsync(data);
        }
        
        public void PublishVoice(byte[] data) {
            base.Channel.PublishVoice(data);
        }
        
        public System.Threading.Tasks.Task PublishVoiceAsync(byte[] data) {
            return base.Channel.PublishVoiceAsync(data);
        }
        
        public string PublishText(string data) {
            return base.Channel.PublishText(data);
        }
        
        public System.Threading.Tasks.Task<string> PublishTextAsync(string data) {
            return base.Channel.PublishTextAsync(data);
        }
    }
}
