//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCast.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppCastEntities : DbContext
    {
        public AppCastEntities()
            : base("name=AppCastEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<KeyManager> KeyManagers { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileShare> FileShares { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
    }
}
