//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.Chats = new HashSet<Chat>();
            this.Files = new HashSet<File>();
            this.FileShares = new HashSet<FileShare>();
        }
    
        public string userID { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string passwordSalt { get; set; }
        public bool enable2fa { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public int role { get; set; }
    
        public virtual Role Role1 { get; set; }
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<FileShare> FileShares { get; set; }
    }
}
