//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int messageID { get; set; }
        public int roomID { get; set; }
        public string userID { get; set; }
        public string message { get; set; }
        public System.DateTime messageDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Room Room { get; set; }
    }
}
