//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.FileShares = new HashSet<FileShare>();
        }
    
        public int fileID { get; set; }
        public string filePath { get; set; }
        public string fileName { get; set; }
        public string fileDesc { get; set; }
        public string uploadDate { get; set; }
        public string uploaderID { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual ICollection<FileShare> FileShares { get; set; }
    }
}
