//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyManager
    {
        public KeyManager()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int keyID { get; set; }
        public string symKey { get; set; }
        public string symKey2 { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
