//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCast.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Chats = new HashSet<Chat>();
        }
    
        public int roomID { get; set; }
        public string roomTitle { get; set; }
        public string roomUser { get; set; }
        public int keyID { get; set; }
        public System.DateTime createDate { get; set; }
        public string createUser { get; set; }
    
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual KeyManager KeyManager { get; set; }
    }
}
